services:
  qc.acc_stinky-violet-magpie:
    command: sleep 6000000
    image: alpine:48.2.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
